#file: noinspection SpellCheckingInspection
version: "3.8"
services:
  backend:
    build: .
    container_name: nhsf-backend
    networks:
      - nhsf_postgres_network
    env_file:
      - $PWD/.env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: $PWD
        target: /app
  postgres:
    image: postgres:11-alpine
    container_name: nhsf-db
    networks:
      - nhsf_postgres_network
    hostname: nhsf-db
    environment:
      POSTGRES_DB: nhsf_backend
      POSTGRES_USER: rc
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

networks:
    nhsf_postgres_network:
