"""
added morning sport and afternoon sport

Revision ID: 1721bffced8a
Revises: 298282bb3319
Created Date: 2024-01-11 22:14:29.943110+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1721bffced8a"
down_revision = "298282bb3319"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chapters", "zone")
    op.drop_column("chapters", "email")
    op.add_column("players", sa.Column("morning_team_id", sa.UUID(), nullable=False))
    op.add_column("players", sa.Column("away_team_id", sa.UUID(), nullable=False))
    op.drop_constraint("players_team_id_fkey", "players", type_="foreignkey")
    op.create_foreign_key(
        None, "players", "teams", ["away_team_id"], ["id"], ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "players", "teams", ["morning_team_id"], ["id"], ondelete="CASCADE",
    )
    op.drop_column("players", "team_id")
    op.add_column("teams", sa.Column("internal_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "internal_name")
    op.add_column(
        "players", sa.Column("team_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "players", type_="foreignkey")
    op.drop_constraint(None, "players", type_="foreignkey")
    op.create_foreign_key(
        "players_team_id_fkey",
        "players",
        "teams",
        ["team_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("players", "away_team_id")
    op.drop_column("players", "morning_team_id")
    op.add_column(
        "chapters", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "chapters", sa.Column("zone", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
