"""
head

Revision ID: 28c7e9aaabef
Revises: ba3b5e6a653e
Created Date: 2024-01-20 21:33:55.326771+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "28c7e9aaabef"
down_revision = "ba3b5e6a653e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams", sa.Column("regional_competition_id", sa.Integer(), nullable=True)
    )
    op.add_column("teams", sa.Column("stage_reached", sa.Integer(), nullable=True))
    op.add_column(
        "teams",
        sa.Column("average_point_per_game_in_group_stage", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "average_point_per_game_in_group_stage")
    op.drop_column("teams", "stage_reached")
    op.drop_column("teams", "regional_competition_id")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""
    pass


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
    pass
