"""
added quarter finals and semi finals to sports table

Revision ID: 2bf8a7b1033b
Revises: 8d140d0957fb
Created Date: 2023-11-08 17:13:59.373802+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2bf8a7b1033b"
down_revision = "8d140d0957fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sports",
        sa.Column(
            "quarter_finals", sa.Boolean(), server_default="false", nullable=False,
        ),
    )
    op.add_column(
        "sports",
        sa.Column("semi_finals", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sports", "semi_finals")
    op.drop_column("sports", "quarter_finals")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
