"""
updated foreign key constraint

Revision ID: 3aa222a8e0d6
Revises: 698a6a76d651
Created Date: 2023-10-09 09:24:21.184238+01:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3aa222a8e0d6"
down_revision = "698a6a76d651"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("matches", "stage_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint("matches_stage_id_fkey", "matches", type_="foreignkey")
    op.create_foreign_key(
        None, "matches", "stages", ["stage_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "matches", type_="foreignkey")
    op.create_foreign_key(
        "matches_stage_id_fkey", "matches", "stages", ["stage_id"], ["id"]
    )
    op.alter_column("matches", "stage_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""
    pass


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
    pass
