"""
add sports params

Revision ID: 3b689a31d465
Revises: e794a05d622f
Created Date: 2024-02-08 13:58:23.159568+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3b689a31d465"
down_revision = "e794a05d622f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sports", sa.Column("number_of_players", sa.Integer(), nullable=True))
    op.add_column(
        "sports",
        sa.Column("morning_sport", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sports", "morning_sport")
    op.drop_column("sports", "number_of_players")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""
    pass


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
    pass
