"""
head

Revision ID: 459552c9a357
Revises: 1721bffced8a
Created Date: 2024-01-17 22:07:34.808095+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "459552c9a357"
down_revision = "1721bffced8a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("afternoon_team_id", sa.UUID(), nullable=False))
    op.drop_constraint("players_away_team_id_fkey", "players", type_="foreignkey")
    op.create_foreign_key(
        None, "players", "teams", ["afternoon_team_id"], ["id"], ondelete="CASCADE",
    )
    op.drop_column("players", "away_team_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "players",
        sa.Column("away_team_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "players", type_="foreignkey")
    op.create_foreign_key(
        "players_away_team_id_fkey",
        "players",
        "teams",
        ["away_team_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("players", "afternoon_team_id")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
