"""
added sport_id column to pitches

Revision ID: 6479400f1880
Revises: c2a070d111d9
Created Date: 2023-11-05 14:15:47.411655+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6479400f1880"
down_revision = "c2a070d111d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pitches", sa.Column("sport_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "pitches", "sports", ["sport_id"], ["id"], ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pitches", type_="foreignkey")
    op.drop_column("pitches", "sport_id")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
