"""
removed cascade on delete for stage from matches

Revision ID: 698a6a76d651
Revises: b6b39260c666
Created Date: 2023-10-06 19:07:53.719776+01:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "698a6a76d651"
down_revision = "b6b39260c666"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "league_tables",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("sport_id", sa.UUID(), nullable=False),
        sa.Column("won", sa.Integer(), server_default="0", nullable=True),
        sa.Column("drawn", sa.Integer(), server_default="0", nullable=True),
        sa.Column("lost", sa.Integer(), server_default="0", nullable=True),
        sa.Column(
            "score_difference",
            sa.NUMERIC(precision=12, scale=2),
            server_default="0",
            nullable=True,
        ),
        sa.Column("played", sa.Integer(), server_default="0", nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "timezone('Europe/London', CURRENT_TIMESTAMP)",
            ),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_modified_date", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["sport_id"], ["sports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_league_tables_id"), "league_tables", ["id"], unique=False)
    op.alter_column("matches", "stage_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("matches_stage_id_fkey", "matches", type_="foreignkey")
    op.create_foreign_key(None, "matches", "stages", ["stage_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "matches", type_="foreignkey")
    op.create_foreign_key(
        "matches_stage_id_fkey",
        "matches",
        "stages",
        ["stage_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("matches", "stage_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_index(op.f("ix_league_tables_id"), table_name="league_tables")
    op.drop_table("league_tables")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
