"""
added match audit table

Revision ID: 7aaf27f2854e
Revises: 2bf8a7b1033b
Created Date: 2023-11-17 15:37:08.299058+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7aaf27f2854e"
down_revision = "2bf8a7b1033b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match_audit",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Europe/London', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_modified_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("match_id", sa.UUID(), nullable=True),
        sa.Column("actioner", sa.String(), nullable=True),
        sa.Column("home_score", sa.NUMERIC(precision=12, scale=2), nullable=True),
        sa.Column("away_score", sa.NUMERIC(precision=12, scale=2), nullable=True),
        sa.Column("home_penalties", sa.NUMERIC(precision=12, scale=2), nullable=True),
        sa.Column("away_penalties", sa.NUMERIC(precision=12, scale=2), nullable=True),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_match_audit_id"), "match_audit", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_audit_id"), table_name="match_audit")
    op.drop_table("match_audit")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""
    pass


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
    pass
