"""
fixed morning and afternoon team id keys

Revision ID: 7bfff76d81b9
Revises: c9a9361c8c5a
Created Date: 2024-01-24 00:36:14.117490+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7bfff76d81b9"
down_revision = "c9a9361c8c5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "players", "morning_team_id", existing_type=sa.UUID(), nullable=True,
    )
    op.alter_column(
        "players", "afternoon_team_id", existing_type=sa.UUID(), nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "players", "afternoon_team_id", existing_type=sa.UUID(), nullable=False,
    )
    op.alter_column(
        "players", "morning_team_id", existing_type=sa.UUID(), nullable=False,
    )
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
