"""
head

Revision ID: 8fcaa4ae2ac1
Revises: b6086f0ed781
Created Date: 2024-01-27 15:53:22.239676+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8fcaa4ae2ac1"
down_revision = "b6086f0ed781"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spectators",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Europe/London', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_modified_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chapter_id", sa.UUID(), nullable=True),
        sa.Column("order_id", sa.String(), nullable=True),
        sa.Column("ticket_id", sa.String(), nullable=True),
        sa.Column("barcode", sa.String(), nullable=True),
        sa.Column("checked_in", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "ticket_voided",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("emergency_contact_name", sa.String(), nullable=True),
        sa.Column("emergency_contact_number", sa.String(), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(), nullable=True),
        sa.Column("allergies_medical_conditions", sa.String(), nullable=True),
        sa.Column("original_chapter", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_spectators_id"), "spectators", ["id"], unique=False)
    op.add_column(
        "players",
        sa.Column(
            "ticket_voided",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "players",
        sa.Column("emergency_contact_name", sa.String(), nullable=True),
    )
    op.add_column(
        "players",
        sa.Column("emergency_contact_number", sa.String(), nullable=True),
    )
    op.add_column(
        "players",
        sa.Column("emergency_contact_phone", sa.String(), nullable=True),
    )
    op.add_column(
        "players",
        sa.Column("allergies_medical_conditions", sa.String(), nullable=True),
    )
    op.add_column("players", sa.Column("original_chapter", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "original_chapter")
    op.drop_column("players", "allergies_medical_conditions")
    op.drop_column("players", "emergency_contact_phone")
    op.drop_column("players", "emergency_contact_number")
    op.drop_column("players", "emergency_contact_name")
    op.drop_column("players", "ticket_voided")
    op.drop_index(op.f("ix_spectators_id"), table_name="spectators")
    op.drop_table("spectators")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
