"""
added internal name to teams tabl

Revision ID: 95493eaa3322
Revises: 298282bb3319
Created Date: 2024-01-06 10:46:54.154724+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "95493eaa3322"
down_revision = "298282bb3319"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("team_id", sa.UUID(), nullable=False))
    op.drop_constraint("players_morning_team_id_fkey", "players", type_="foreignkey")
    op.drop_constraint("players_afternoon_team_id_fkey", "players", type_="foreignkey")
    op.create_foreign_key(
        None, "players", "teams", ["team_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("players", "afternoon_team_id")
    op.drop_column("players", "morning_team_id")
    op.add_column("teams", sa.Column("internal_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "internal_name")
    op.add_column(
        "players",
        sa.Column("morning_team_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "players",
        sa.Column("afternoon_team_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "players", type_="foreignkey")
    op.create_foreign_key(
        "players_afternoon_team_id_fkey",
        "players",
        "teams",
        ["afternoon_team_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "players_morning_team_id_fkey",
        "players",
        "teams",
        ["morning_team_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("players", "team_id")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""
    pass


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
    pass
