"""
make username unique

Revision ID: a81fe7c87882
Revises: 86f881da9d07
Created Date: 2023-09-14 22:33:17.612612+01:00

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "a81fe7c87882"
down_revision = "86f881da9d07"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("username_unique", "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("username_unique", "users", type_="unique")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
