"""
head

Revision ID: ba3b5e6a653e
Revises: a90201d82a31
Created Date: 2024-01-20 16:35:36.934082+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ba3b5e6a653e"
down_revision = "a90201d82a31"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sports", sa.Column("start_time", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sports", "start_time")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""
    pass


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
    pass
