"""
fixed relation column

Revision ID: cad1672d5a1c
Revises: d261d3506a18
Created Date: 2024-01-27 20:41:42.815660+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cad1672d5a1c"
down_revision = "d261d3506a18"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "players",
        sa.Column("emergency_contact_relation", sa.String(), nullable=True),
    )
    op.drop_column("players", "emergency_contact_phone")
    op.add_column(
        "spectators",
        sa.Column("emergency_contact_relation", sa.String(), nullable=True),
    )
    op.drop_column("spectators", "emergency_contact_phone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spectators",
        sa.Column(
            "emergency_contact_phone",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("spectators", "emergency_contact_relation")
    op.add_column(
        "players",
        sa.Column(
            "emergency_contact_phone",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("players", "emergency_contact_relation")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
