"""
added_tickets_columns

Revision ID: e794a05d622f
Revises: cad1672d5a1c
Created Date: 2024-02-01 19:13:00.688000+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "e794a05d622f"
down_revision = "cad1672d5a1c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("chapter", sa.String(), nullable=True),
        sa.Column("original_chapter", sa.String(), nullable=True),
        sa.Column("morning_sport", sa.String(), nullable=True),
        sa.Column("afternoon_sport", sa.String(), nullable=True),
        sa.Column("emergency_contact_name", sa.String(), nullable=True),
        sa.Column("emergency_contact_number", sa.String(), nullable=True),
        sa.Column("emergency_contact_relationship", sa.String(), nullable=True),
        sa.Column("allergies_medical_conditions", sa.String(), nullable=True),
        sa.Column("order_id", sa.String(), nullable=True),
        sa.Column("ticket_id", sa.String(), nullable=True),
        sa.Column("barcode", sa.String(), nullable=True),
        sa.Column("checked_in", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "ticket_voided",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "update_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("spectator_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Europe/London', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_modified_date", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["spectator_id"],
            ["spectators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tickets_id"), "tickets", ["id"], unique=False)
    op.drop_column("players", "ticket_id")
    op.drop_column("players", "order_id")
    op.drop_column("players", "emergency_contact_number")
    op.drop_column("players", "emergency_contact_name")
    op.drop_column("players", "original_chapter")
    op.drop_column("players", "emergency_contact_relation")
    op.drop_column("players", "ticket_voided")
    op.drop_column("players", "barcode")
    op.drop_column("players", "allergies_medical_conditions")
    op.drop_column("players", "checked_in")
    op.drop_constraint("spectators_chapter_id_fkey", "spectators", type_="foreignkey")
    op.drop_column("spectators", "chapter_id")
    op.drop_column("spectators", "ticket_id")
    op.drop_column("spectators", "order_id")
    op.drop_column("spectators", "emergency_contact_number")
    op.drop_column("spectators", "emergency_contact_name")
    op.drop_column("spectators", "original_chapter")
    op.drop_column("spectators", "emergency_contact_relation")
    op.drop_column("spectators", "ticket_voided")
    op.drop_column("spectators", "barcode")
    op.drop_column("spectators", "allergies_medical_conditions")
    op.drop_column("spectators", "checked_in")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spectators",
        sa.Column(
            "checked_in",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "spectators",
        sa.Column(
            "allergies_medical_conditions",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "spectators",
        sa.Column("barcode", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "spectators",
        sa.Column(
            "ticket_voided",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "spectators",
        sa.Column(
            "emergency_contact_relation",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "spectators",
        sa.Column("original_chapter", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "spectators",
        sa.Column(
            "emergency_contact_name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "spectators",
        sa.Column(
            "emergency_contact_number",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "spectators",
        sa.Column("order_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "spectators",
        sa.Column("ticket_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "spectators",
        sa.Column("chapter_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "spectators_chapter_id_fkey",
        "spectators",
        "chapters",
        ["chapter_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "players",
        sa.Column(
            "checked_in",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "players",
        sa.Column(
            "allergies_medical_conditions",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "players",
        sa.Column("barcode", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "players",
        sa.Column(
            "ticket_voided",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "players",
        sa.Column(
            "emergency_contact_relation",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "players",
        sa.Column("original_chapter", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "players",
        sa.Column(
            "emergency_contact_name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "players",
        sa.Column(
            "emergency_contact_number",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "players",
        sa.Column("order_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "players",
        sa.Column("ticket_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_tickets_id"), table_name="tickets")
    op.drop_table("tickets")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
