"""
changed columns

Revision ID: f77e349958a4
Revises: 3aa222a8e0d6
Created Date: 2023-11-01 17:52:30.372144+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f77e349958a4"
down_revision = "3aa222a8e0d6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "league_tables",
        sa.Column(
            "scores_for",
            sa.NUMERIC(precision=12, scale=2),
            server_default="0",
            nullable=True,
        ),
    )
    op.add_column(
        "league_tables",
        sa.Column(
            "scores_against",
            sa.NUMERIC(precision=12, scale=2),
            server_default="0",
            nullable=True,
        ),
    )
    op.drop_column("league_tables", "score_difference")
    op.add_column("teams", sa.Column("group", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "group")
    op.add_column(
        "league_tables",
        sa.Column(
            "score_difference",
            sa.NUMERIC(precision=12, scale=2),
            server_default=sa.text("'0'::numeric"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("league_tables", "scores_against")
    op.drop_column("league_tables", "scores_for")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
