"""
head

Revision ID: f8bbb6804eef
Revises: 7bfff76d81b9
Created Date: 2024-01-25 00:52:31.046668+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f8bbb6804eef"
down_revision = "7bfff76d81b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("order_id", sa.String(), nullable=True))
    op.add_column("players", sa.Column("ticket_id", sa.String(), nullable=True))
    op.add_column(
        "players",
        sa.Column("checked_in", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "checked_in")
    op.drop_column("players", "ticket_id")
    op.drop_column("players", "order_id")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""
    pass


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
    pass
