name: Docker

on:
  push:
    branches:
      - development

jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:

        - name: Checkout
          uses: actions/checkout@v3

        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    
        - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v1
    
        - name: Use gcloud CLI
          run: gcloud info
          
        - name: Configure Docker
          run: gcloud auth configure-docker --quiet


        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_APP_NAME }} --quiet --image $IMAGE_NAME --platform managed --project ${{ secrets.GCP_PROJECT_ID }} --memory 256Mi --timeout 300 --concurrency 100 --max-instances 1000 --cpu 1 --clear-env-vars --clear-cloudsql-instances --client-name "Github Actions" --region europe-west1 --allow-unauthenticated --clear-vpc-connector